# Generated by Django 4.2.7 on 2024-01-28 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_booking_reservation_date_booking_reservation_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
